baseurl = "https://du1ab.one/"
languageCode = "zh-cn"
title = "Wuan's Blog"
theme = "ezhil"
paginate = 5
summaryLength = 10
copyright = "Copyleft ğŸ„¯ 2006-2021"
disqusShortname = "s5unty"
enableEmoji = true

[permalinks]
posts = "/:year/:title/"

[markup]
  [markup.highlight]
    # å†…ç½®çš„ chroma é«˜äº®ï¼Œå¯¹ asciidoc æ”¯æŒä¸å¥½
    # æ˜ç¡®ç¦ç”¨ï¼Œé¿å…å’Œ highlight.js é‡å¤é«˜äº®
    codeFences = false
  [markup.asciidocExt.attributes]
    hardbreaks = true
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = false
      xhtml = false

[params]
subtitle = "å°±åœ°æ­£æ³•ä¹…ä½"
disableDisqusTypes = ["page"]
featherIconsCDN = true
mode = "auto" # "dark", "auto", "light"
customCSS = ["css/fonts.css", "css/github.min.css"]  # Custom CSS applied to default styles.
# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
customJS = ["js/highlight.min.js"]  # Custom JS scripts.

[[menu.main]]
name = "Root"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/s5unty"

[[params.social]]
name = "Theravada"
icon = "settings"
url = "https://www.remnote.io/a/60f6b397fd7c910034210b93"

[taxonomies]
tag = "tags"

